#!/bin/bash

# SSH/SFTP push site
# Transfers resume files from localhost to remote server
# on a digital ocean droplet


# First, ssh in and make sure the prequisite directories are created
ssh matt@192.81.213.200 '\
cd /var/www/resume.mattsheehan.me/public_html;\
create_dir(){ if [ ! -d $1 ]; then mkdir $1; fi };\
create_dir assets;\
create_dir external;'



# Then sftp in and use the put command to copy files from localhost
# to the server
sftp matt@192.81.213.200 <<EOF
cd /var/www/resume.mattsheehan.me/public_html
put /home/matt/Dropbox/projects/resume/resume.mattsheehan.me/build/index.html
put /home/matt/Dropbox/projects/resume/resume.mattsheehan.me/build/robots.txt
put /home/matt/Dropbox/projects/resume/resume.mattsheehan.me/build/humans.txt
put /home/matt/Dropbox/projects/resume/resume.mattsheehan.me/build/Matthew-Sheehan-PDF.pdf

put -r /home/matt/Dropbox/projects/resume/resume.mattsheehan.me/build/assets
put -r /home/matt/Dropbox/projects/resume/resume.mattsheehan.me/build/external
EOF
